# Generated by Django 2.1.7 on 2019-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('created_by', models.CharField(default='User', max_length=256)),
                ('code_language', models.CharField(max_length=30)),
                ('folder_location', models.CharField(max_length=128)),
                ('uploaded_code', models.FileField(upload_to='')),
                ('description', models.CharField(default='Type Here...', max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('EONid', models.CharField(max_length=256)),
            ],
        ),
    ]
