# Generated by Django 2.1.7 on 2019-03-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='EONid',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='uploaded_code',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='executable_file_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='code_language',
            field=models.CharField(choices=[('0', 'C'), ('1', 'Python')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
