# Generated by Django 2.1.7 on 2019-03-12 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete='remove', related_name='u_f', to=settings.AUTH_USER_MODEL)),
                ('viewing_user', models.ForeignKey(null=True, on_delete='remove', related_name='vu_f', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete='remove', related_name='u_fr', to=settings.AUTH_USER_MODEL)),
                ('viewing_user', models.ForeignKey(null=True, on_delete='remove', related_name='vu_fr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
