# Generated by Django 2.1.7 on 2019-03-12 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 13, 58, 20, 189263)),
        ),
    ]
