# Generated by Django 2.1.7 on 2019-03-12 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190312_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 15, 7, 51, 517875)),
        ),
    ]
