# Generated by Django 2.1.7 on 2019-03-13 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190312_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 22, 29, 56, 696205)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 22, 29, 56, 695207)),
        ),
    ]
